version: '3'
services:
  mongodb:
    image: mongo
    port:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example 
    volumes: 
      - mongo-data:/data/db       
  mongo-express:
    image: mongo-express
    restart: always  
    port: 
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb 
volumes: 
  mongo-data:
    driver: local 
